<?php

/**
 * @file product_catalog.install
 */

/**
 * Implements hook_install().
 */

function product_catalog_install() {
  variable_set('pathauto_node_catalog_product_pattern', 'product-catalog/[node:title]');
  $settings = field_bundle_settings('node', 'catalog_product');
  $settings['view_modes']['colorbox']['custom_settings'] = TRUE;
  field_bundle_settings('node', 'catalog_product', $settings);
}
