<?php

use Drupal\views\ViewExecutable;

/**
 * Implements hook_views_pre_render().
 */
function product_catalog_views_pre_render(ViewExecutable $view) {
  if (isset($view) && ($view->storage->id() == 'product_catalog')) {
    $view->element['#attached']['library'][] = 'product_catalog/product-catalog';
  }
}

/**
 * Implements hook_preprocess_node().
 */
function product_catalog_preprocess_node(&$variables) {
  $node = $variables['node'];
  
  if ($node->getType() == 'catalog_product') {
    $variables['#attached']['library'][] = 'product_catalog/product-catalog';
  }
}

/**
 * Implements hook_theme().
 */
function product_catalog_theme($existing, $type, $theme, $path) {
  return [
    'node__catalog_product' => [
      'template' => 'node--catalog-product',
      'base hook' => 'node',
    ],
    'views_view__product_catalog__page' => [
      'template' => 'views-view--product-catalog--page',
      'base hook' => 'views',
    ],
    'views_view_unformatted__product_catalog' => [
      'template' => 'views-view-unformatted--product-catalog',
      'base hook' => 'views',
    ],
  ];
}