<?php
/**
 * @file
 * Code for the Product Catalog feature.
 */

include_once 'product_catalog.features.inc';

// =====================
// = Add Node Template =
// =====================

/**
 * Implements hook_theme().
 */
function product_catalog_theme($existing, $type, $theme, $path) {
  $theme = array();
  $theme['node__catalog_product'] = array(
    'render element' => 'content',
    'base hook' => 'node',
    'template' => 'node--catalog_product',
    'path' => drupal_get_path('module', 'product_catalog') . '/templates',
  );
  return $theme;
}

// =================================
// = Implements hook_permission(). =
// =================================

function product_catalog_permission() {
  $permission = array(
    'administer product catalog' => array(
      'title' => t('Administer Product Catalog'),
      'description' => t('Configure Product Catalog settings.'),
    ),
  );
  return $permission;
}

// ===========================
// = Implements hook_menu(). =
// ===========================

function product_catalog_menu() {
  $items['admin/config/services/copier-catalog'] = array(
    'title' => t('Copier Catalog Settings'),
    'description' => t('Configure Copier Catalog Settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('product_catalog_admin_settings'),
    'access arguments' => array('administer product catalog'),
  );
  return $items;
}

// ==================================
// = Construct admin settings form. =
// ==================================

function product_catalog_admin_settings($form, &$form_state) {
  $form['help_txt'] = array(
    '#markup' => '<div class="help-txt">Visit <a href="https://www.copiercatalog.com/user">Copier Catalog</a> to create a user account, and retrieve the User ID for the client.</div>',
  );
  $form['cc_uid'] = array(
    '#title' => t('Copier Catalog User ID'),
    '#type' => 'textfield',
    '#description' => t('Enter the user ID for the account created on www.copiercatalog.com.'),
    '#default_value' => variable_get('cc_uid', ''),
    '#attributes' => array('placeholder' => 'UID'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save Configuration'),
    '#submit' => array('product_catalog_admin_settings_submit'),
  );
  return $form;
}

// ==============================
// = Admin form submit handler. =
// ==============================

function product_catalog_admin_settings_submit(&$form, &$form_state) {
  global $user;
  
  $cc_uid = $form_state['values']['cc_uid'];
  variable_set('cc_uid', $cc_uid);
  $node = new stdClass();
  $node->title = 'Catalog Feed ' . $cc_uid;
  $node->type = 'catalog_feed';
  node_object_prepare($node);
  $node->language = LANGUAGE_NONE;
  $node->uid = $user->uid;
  $node->status = 1;
  $node->promote = 0;
  $node->comment = 0;
  $node->feeds['FeedsHTTPFetcher']['source'] = 'http://www.copiercatalog.com/catalog-product/xml/' . $cc_uid;
  
  $node = node_submit($node);
  node_save($node);
}